services:
  db:
    image: postgres:15
    container_name: nfl_db
    restart: always
    environment:
      POSTGRES_USER: fantasy_admin
      POSTGRES_PASSWORD: "Sdf18943!@!"
      POSTGRES_DB: fantasy_league_Tank01_Data
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fantasy_admin -d fantasy_league_Tank01_Data"]
      interval: 5s
      timeout: 5s
      retries: 5

  engine-python:
    build: ./engine-python
    container_name: nfl_engine
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_NAME: fantasy_league_Tank01_Data
      DB_USER: fantasy_admin
      DB_PASS: "Sdf18943!@!"
      RAPIDAPI_KEY: "dfda76b64dmshc04842ad36742b9p199581jsndcfb1b5bd1b2"

  backend-node:
    build: ./backend-node
    container_name: nfl_web
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_NAME: fantasy_league_Tank01_Data
      DB_USER: fantasy_admin
      DB_PASS: "Sdf18943!@!"